version: '3.8'

services:
  django_frontend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db_app2
    networks:
      - shared_network

  db_app2:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_django:/var/lib/postgresql/data
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  postgres_data_django: