# Generated by Django 5.1.3 on 2024-11-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='fastapi_doc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
