# Generated by Django 5.1.3 on 2024-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_django', '0002_doc_fastapi_doc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='file_path',
        ),
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
