# Generated by Django 5.1.3 on 2024-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_django', '0003_remove_doc_file_path_doc_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='file',
        ),
        migrations.AddField(
            model_name='doc',
            name='file_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doc',
            name='fastapi_doc_id',
            field=models.IntegerField(null=True),
        ),
    ]
