# Generated by Django 5.1.3 on 2024-11-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_django', '0004_remove_doc_file_doc_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='docs_id',
        ),
    ]
