# Generated by Django 5.1.3 on 2024-12-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_django', '0005_remove_price_docs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='fastapi_doc_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
